import { Product } from '@/components/shopping/ProductCard';

export const sportsProducts: Product[] = [
  // ============ QUẦN ÁO THỂ THAO (Products 1-5, 25-27) ============
  {
    id: '1',
    name: 'Men\'s Performance Training T-Shirt',
    description: 'Breathable moisture-wicking training shirt designed for high-intensity workouts. Quick-dry fabric keeps you cool and comfortable.',
    price: 49.99,
    image: '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Moss-1.webp',
    images: [
      '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Moss-1.webp',
      '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Moss-2.webp',
      '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Moss-3.webp',
      '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Moss-4.webp',
      '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Moss-5.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Moisture-wicking fabric technology',
      'Quick-dry material',
      'Anti-odor treatment',
      'Breathable mesh panels',
      'Stretchy 4-way material',
    ],
    specifications: {
      'Material': '88% Polyester, 12% Spandex',
      'Sizes': 'S, M, L, XL, XXL',
      'Care': 'Machine washable',
      'Fit': 'Athletic fit',
    },
  },
  {
    id: '2',
    name: 'Women\'s High-Waist Yoga Leggings',
    description: 'Premium compression leggings with pocket. Perfect for yoga, running, or gym workouts. Squat-proof and non-see-through.',
    price: 44.99,
    image: '/products/M-Model-Mens-AeroFLX-Seamless-Long-Sleeve-Tee-Black-Marl-1.webp',
    images: [
      '/products/M-Model-Mens-AeroFLX-Seamless-Long-Sleeve-Tee-Black-Marl-1.webp',
      '/products/M-Model-Mens-AeroFLX-Seamless-Long-Sleeve-Tee-Black-Marl-2.webp',
      '/products/M-Model-Mens-AeroFLX-Seamless-Long-Sleeve-Tee-Black-Marl-3.webp',
      '/products/M-Model-Mens-AeroFLX-Seamless-Long-Sleeve-Tee-Black-Marl-Fabric-Texture-1.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'High-waist design for tummy control',
      'Hidden pocket for essentials',
      'Squat-proof fabric',
      'Non-see-through material',
      'Moisture-wicking technology',
    ],
    specifications: {
      'Material': '79% Nylon, 21% Spandex',
      'Sizes': 'XS, S, M, L, XL',
      'Care': 'Machine washable cold',
      'Rise': 'High-rise (10-12 inches)',
    },
  },
  {
    id: '3',
    name: 'Men\'s Training Compression Tee',
    description: 'Advanced compression shirt for enhanced performance. Designed for CrossFit, running, and intense training sessions.',
    price: 39.99,
    image: '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Storm-1.webp',
    images: [
      '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Storm-1.webp',
      '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Storm-2.webp',
      '/products/M-Model-Mens-AeroFLX_-Seamless-Long-Sleeve-Tee-Dark-Storm-3.webp',
    ],
    category: 'Clothing',
    rating: 4,
    inStock: true,
    features: [
      'Compression fit for muscle support',
      'Flat-lock seams prevent chafing',
      'Quick-dry technology',
      'UV protection',
      'Reflective details for visibility',
    ],
    specifications: {
      'Material': '85% Polyester, 15% Elastane',
      'Sizes': 'S, M, L, XL',
      'Care': 'Machine wash cold',
      'Fit': 'Compression fit',
    },
  },
  {
    id: '4',
    name: 'Women\'s Oversized Training Tee',
    description: 'Comfortable oversized fit perfect for casual workouts and athleisure. Soft, breathable fabric with trendy design.',
    price: 34.99,
    image: '/products/L-Model-Power-Oversized-Tee-Tradewinds-Washed-1.webp',
    images: [
      '/products/L-Model-Power-Oversized-Tee-Tradewinds-Washed-1.webp',
      '/products/L-Model-Power-Oversized-Tee-Tradewinds-Washed-2.webp',
      '/products/L-Model-Power-Oversized-Tee-Tradewinds-Washed-3.webp',
      '/products/L-Model-Power-Oversized-Tee-Tradewinds-Washed-4.webp',
      '/products/L-Model-Power-Oversized-Tee-Tradewinds-Washed-5.webp',
      '/products/L-Model-Power-Oversized-Tee-Tradewinds-Washed-6.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Relaxed oversized fit',
      'Soft cotton blend fabric',
      'Dropped shoulder design',
      'Curved hem',
      'Breathable and lightweight',
    ],
    specifications: {
      'Material': '60% Cotton, 40% Polyester',
      'Sizes': 'XS, S, M, L, XL',
      'Care': 'Machine washable',
      'Fit': 'Oversized',
    },
  },
  {
    id: '5',
    name: 'Men\'s Half-Zip Training Top',
    description: 'Versatile half-zip top for layering. Perfect for warm-ups, cool-downs, and outdoor training sessions.',
    price: 54.99,
    image: '/products/L-Model-Mens-AeroFLX-Seamless-Half-Zip-Long-Sleeve-Tee-Black-1.webp',
    images: [
      '/products/L-Model-Mens-AeroFLX-Seamless-Half-Zip-Long-Sleeve-Tee-Black-1.webp',
      '/products/L-Model-Mens-AeroFLX-Seamless-Half-Zip-Long-Sleeve-Tee-Black-2.webp',
      '/products/L-Model-Mens-AeroFLX-Seamless-Half-Zip-Long-Sleeve-Tee-Black-3.webp',
      '/products/L-Model-Mens-AeroFLX-Seamless-Half-Zip-Long-Sleeve-Tee-Black-4.webp',
      '/products/L-Model-Mens-AeroFLX-Seamless-Half-Zip-Long-Sleeve-Tee-Black-5.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Half-zip design for ventilation control',
      'Thumbholes for hand coverage',
      'Seamless construction',
      'Moisture-wicking fabric',
      'Athletic fit',
    ],
    specifications: {
      'Material': '88% Polyester, 12% Spandex',
      'Sizes': 'S, M, L, XL, XXL',
      'Care': 'Machine wash cold',
      'Fit': 'Athletic fit',
    },
  },
  
  // ============ GIÀY THỂ THAO (Products 6-14) ============
  {
    id: '6',
    name: 'Women\'s Cross Training Shoes',
    description: 'Versatile training shoes designed for weightlifting, cardio, and high-intensity workouts. Superior stability and comfort.',
    price: 129.99,
    image: '/products/Dropset_3_Training_Shoes_Beige_JR1675_HM1.avif',
    images: [
      '/products/Dropset_3_Training_Shoes_Beige_JR1675_HM1.avif',
      '/products/Dropset_3_Training_Shoes_Beige_JR1675_HM3_hover.avif',
      '/products/Dropset_3_Training_Shoes_Beige_JR1675_HM4.avif',
    ],
    category: 'Footwear',
    rating: 5,
    inStock: true,
    features: [
      'Dual-density midsole for stability',
      'Wide toe box for natural foot splay',
      'Durable rubber outsole',
      'Breathable mesh upper',
      'Reinforced heel for lifting',
    ],
    specifications: {
      'Weight': '285g (US 7)',
      'Drop': '4mm heel-to-toe',
      'Upper': 'Mesh and synthetic overlays',
      'Outsole': 'Rubber with traction pattern',
    },
  },
  {
    id: '7',
    name: 'Men\'s Basketball Sneakers',
    description: 'High-performance basketball shoes with responsive cushioning and excellent court grip. Designed for quick movements.',
    price: 139.99,
    image: '/products/Rapidmove_ADV_2_HIIT_training_shoes_White_JI4196_HM1.avif',
    images: [
      '/products/Rapidmove_ADV_2_HIIT_training_shoes_White_JI4196_HM1.avif',
      '/products/Rapidmove_ADV_2_HIIT_training_shoes_White_JI4196_HM3_hover.avif',
      '/products/Rapidmove_ADV_2_HIIT_training_shoes_White_JI4196_HM4.avif',
    ],
    category: 'Footwear',
    rating: 5,
    inStock: true,
    features: [
      'Responsive cushioning system',
      'High-traction rubber outsole',
      'Ankle support collar',
      'Breathable knit upper',
      'Lightweight construction',
    ],
    specifications: {
      'Weight': '320g (US 9)',
      'Drop': '10mm',
      'Upper': 'Engineered knit',
      'Midsole': 'EVA foam',
    },
  },
  {
    id: '8',
    name: 'Adidas Dropset Black Training Shoes',
    description: 'Professional-grade training shoes for serious athletes. Exceptional stability for weightlifting with flexibility for dynamic movements.',
    price: 119.99,
    image: '/products/Dropset_3_Training_Shoes_Black_IH8292_HM1.avif',
    images: [
      '/products/Dropset_3_Training_Shoes_Black_IH8292_HM1.avif',
      '/products/Dropset_3_Training_Shoes_Black_IH8292_HM3_hover.avif',
      '/products/Dropset_3_Training_Shoes_Black_IH8292_HM4.avif',
    ],
    category: 'Footwear',
    rating: 5,
    inStock: true,
    features: [
      'Flat, stable base for lifting',
      'Flexible forefoot for agility',
      'Breathable mesh construction',
      'Durable rubber outsole',
      'Supportive midfoot',
    ],
    specifications: {
      'Weight': '295g',
      'Drop': '3mm',
      'Upper': 'Textile and synthetic',
      'Sole': 'Rubber',
    },
  },
  {
    id: '9',
    name: 'Adidas Dropset White Training Shoes',
    description: 'Stylish white training shoes combining fashion and function. Perfect for gym workouts and casual wear.',
    price: 119.99,
    image: '/products/Dropset_3_Training_Shoes_White_ID8633_HM1.avif',
    images: [
      '/products/Dropset_3_Training_Shoes_White_ID8633_HM1.avif',
      '/products/Dropset_3_Training_Shoes_White_ID8633_HM3_hover.avif',
      '/products/Dropset_3_Training_Shoes_White_ID8633_HM4.avif',
    ],
    category: 'Footwear',
    rating: 5,
    inStock: true,
    features: [
      'Clean white colorway',
      'Versatile training shoe',
      'Stable platform for lifting',
      'Comfortable all-day wear',
      'Easy to clean material',
    ],
    specifications: {
      'Weight': '295g',
      'Drop': '3mm',
      'Upper': 'Synthetic leather',
      'Sole': 'Rubber',
    },
  },
  {
    id: '10',
    name: 'Men\'s Training Shorts - Purple',
    description: 'Lightweight training shorts with moisture-wicking fabric. Perfect for running, gym, and sports activities.',
    price: 29.99,
    image: '/products/Designed-for-Training_Legacy_Shorts_Purple_KA5287_21_model.avif',
    images: [
      '/products/Designed-for-Training_Legacy_Shorts_Purple_KA5287_21_model.avif',
      '/products/Designed-for-Training_Legacy_Shorts_Purple_KA5287_23_hover_model.avif',
      '/products/Designed-for-Training_Legacy_Shorts_Purple_KA5287_25_model.avif',
    ],
    category: 'Clothing',
    rating: 4,
    inStock: true,
    features: [
      'Elastic waistband with drawstring',
      'Side pockets for storage',
      'Quick-dry fabric',
      'Lightweight and breathable',
      '7-inch inseam',
    ],
    specifications: {
      'Material': '100% Polyester',
      'Sizes': 'S, M, L, XL',
      'Inseam': '7 inches',
      'Care': 'Machine washable',
    },
  },
  {
    id: '11',
    name: 'Men\'s Training Shorts - Black',
    description: 'Classic black training shorts for versatile workout sessions. Comfortable fit with functional pockets.',
    price: 29.99,
    image: '/products/Designed-for-Training_Legacy_Shorts_Black_KA5283_21_model.avif',
    images: [
      '/products/Designed-for-Training_Legacy_Shorts_Black_KA5283_21_model.avif',
      '/products/Designed-for-Training_Legacy_Shorts_Black_KA5283_23_hover_model.avif',
      '/products/Designed-for-Training_Legacy_Shorts_Black_KA5283_25_model_hover.avif',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Classic black color',
      'Elastic waistband',
      'Zippered pocket',
      'Moisture-wicking fabric',
      'Athletic fit',
    ],
    specifications: {
      'Material': '100% Polyester',
      'Sizes': 'S, M, L, XL, XXL',
      'Inseam': '7 inches',
      'Care': 'Machine wash cold',
    },
  },
  {
    id: '12',
    name: 'Adidas HIIT Training Shoes - Green',
    description: 'High-intensity interval training shoes with superior grip and flexibility. Designed for explosive movements.',
    price: 134.99,
    image: '/products/Rapidmove_ADV_2_HIIT_training_shoes_Green_IH2707_HM1.avif',
    images: [
      '/products/Rapidmove_ADV_2_HIIT_training_shoes_Green_IH2707_HM1.avif',
      '/products/Rapidmove_ADV_2_HIIT_training_shoes_Green_IH2707_HM3_hover.avif',
      '/products/Rapidmove_ADV_2_HIIT_training_shoes_Green_IH2707_HM4.avif',
      '/products/Rapidmove_ADV_2_HIIT_training_shoes_Green_IH2707_HM5.avif',
    ],
    category: 'Footwear',
    rating: 5,
    inStock: true,
    features: [
      'Lightweight for quick movements',
      'Excellent traction pattern',
      'Flexible for lateral movements',
      'Breathable upper',
      'Responsive cushioning',
    ],
    specifications: {
      'Weight': '260g',
      'Drop': '6mm',
      'Upper': 'Mesh and synthetics',
      'Sole': 'High-traction rubber',
    },
  },
  {
    id: '13',
    name: 'Adidas Rapidmove Training Shoes - Green',
    description: 'Versatile training shoes for mixed workouts. Perfect balance of stability and mobility for diverse training.',
    price: 124.99,
    image: '/products/Rapidmove_ADV_2_Training_Shoes_Green_JI3904_HM1.avif',
    images: [
      '/products/Rapidmove_ADV_2_Training_Shoes_Green_JI3904_HM1.avif',
      '/products/Rapidmove_ADV_2_Training_Shoes_Green_JI3904_HM3_hover.avif',
      '/products/Rapidmove_ADV_2_Training_Shoes_Green_JI3904_HM4.avif',
      '/products/Rapidmove_ADV_2_Training_Shoes_Green_JI3904_HM5.avif',
    ],
    category: 'Footwear',
    rating: 4,
    inStock: true,
    features: [
      'Multi-purpose training shoe',
      'Stable heel for lifting',
      'Flexible forefoot',
      'Breathable design',
      'Durable construction',
    ],
    specifications: {
      'Weight': '280g',
      'Drop': '5mm',
      'Upper': 'Textile',
      'Sole': 'Rubber',
    },
  },
  {
    id: '14',
    name: 'Adidas Training Shoes - Beige',
    description: 'Stylish beige training shoes with premium comfort. Versatile for workouts and everyday wear.',
    price: 114.99,
    image: '/products/Dropset_3_Training_Shoes_Beige_JR1675_HM1.avif',
    images: [
      '/products/Dropset_3_Training_Shoes_Beige_JR1675_HM1.avif',
      '/products/Dropset_3_Training_Shoes_Beige_JR1675_HM3_hover.avif',
      '/products/Dropset_3_Training_Shoes_Beige_JR1675_HM4.avif',
    ],
    category: 'Footwear',
    rating: 5,
    inStock: true,
    features: [
      'Neutral beige color',
      'Comfortable cushioning',
      'Stable training platform',
      'Breathable materials',
      'Stylish design',
    ],
    specifications: {
      'Weight': '290g',
      'Drop': '4mm',
      'Upper': 'Mesh and synthetic',
      'Sole': 'Rubber',
    },
  },

  // ============ THIẾT BỊ GYM (Products 15-24) ============
  {
    id: '15',
    name: 'Professional Treadmill',
    description: 'Commercial-grade treadmill with advanced features. Perfect for home gym setups. Powerful motor and large running surface.',
    price: 1999.99,
    image: '/products/artis-run-700-1.jpg',
    images: [
      '/products/artis-run-700-1.jpg',
      '/products/artis-run-700-2.jpg',
      '/products/artis-run-700-3.jpg',
      '/products/artis-run-700-4.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      'Powerful 3.5 HP motor',
      'Large 22" x 60" running surface',
      '15 preset programs',
      'Heart rate monitoring',
      'Foldable design',
    ],
    specifications: {
      'Motor': '3.5 HP continuous duty',
      'Speed Range': '0.5 - 12 mph',
      'Incline': '0-15% automatic',
      'Max User Weight': '350 lbs',
    },
  },
  {
    id: '16',
    name: 'Indoor Cycling Bike',
    description: 'Studio-quality spin bike with magnetic resistance. Smooth, quiet operation perfect for home workouts.',
    price: 899.99,
    image: '/products/bike-forma-1.jpg',
    images: [
      '/products/bike-forma-1.jpg',
      '/products/bike-forma-2.jpg',
      '/products/bike-forma-3.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      'Magnetic resistance system',
      'Adjustable seat and handlebars',
      'Digital display console',
      'Transport wheels',
      'Water bottle holder',
    ],
    specifications: {
      'Flywheel': '40 lbs',
      'Resistance': 'Magnetic',
      'Max User Weight': '300 lbs',
      'Dimensions': '48" x 21" x 45"',
    },
  },
  {
    id: '17',
    name: 'Professional Elliptical Trainer',
    description: 'Low-impact cardio machine with smooth motion. Features multiple resistance levels and workout programs.',
    price: 1299.99,
    image: '/products/synchro-forma-1.jpg',
    images: [
      '/products/synchro-forma-1.jpg',
      '/products/synchro-forma-2.jpg',
      '/products/synchro-forma-3.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      'Silent magnetic resistance',
      '20" stride length',
      'Moving handlebars',
      '16 resistance levels',
      'Heart rate sensors',
    ],
    specifications: {
      'Stride Length': '20 inches',
      'Resistance Levels': '16',
      'Max User Weight': '350 lbs',
      'Console': 'LCD display',
    },
  },
  {
    id: '18',
    name: 'Multi-Function Smith Machine',
    description: 'Complete strength training system. Includes smith machine, lat pulldown, and cable crossover stations.',
    price: 2499.99,
    image: '/products/pure-strength-1.jpg',
    images: [
      '/products/pure-strength-1.jpg',
      '/products/pure-strength-2.jpg',
      '/products/pure-strength-3.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      'Smith machine with safety catches',
      'Lat pulldown station',
      'Cable crossover system',
      'Multiple grip positions',
      'Weight storage',
    ],
    specifications: {
      'Max Weight': '500 lbs on smith',
      'Cable Weight Stack': '200 lbs each',
      'Dimensions': '90" x 72" x 84"',
      'Frame': 'Commercial-grade steel',
    },
  },
  {
    id: '19',
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving adjustable dumbbells. Replace entire dumbbell rack. Quick weight adjustment system.',
    price: 449.99,
    image: '/products/selection-900-1.jpg',
    images: [
      '/products/selection-900-1.jpg',
      '/products/selection-900-2.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      'Adjustable 5-52.5 lbs per hand',
      'Quick-select dial system',
      'Compact storage tray',
      'Replaces 15 pairs of dumbbells',
      'Durable construction',
    ],
    specifications: {
      'Weight Range': '5-52.5 lbs (per dumbbell)',
      'Increments': '2.5 lbs',
      'Materials': 'Steel and plastic',
      'Warranty': '2 years',
    },
  },
  {
    id: '20',
    name: 'Premium Rowing Machine',
    description: 'Full-body cardio and strength workout. Smooth magnetic resistance with performance monitor.',
    price: 1099.99,
    image: '/products/vario-700-1.jpg',
    images: [
      '/products/vario-700-1.jpg',
      '/products/vario-700-2.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      'Magnetic resistance system',
      'Performance monitor',
      'Ergonomic handle',
      'Adjustable footrests',
      'Foldable for storage',
    ],
    specifications: {
      'Resistance': 'Magnetic',
      'Monitor': 'LCD with multiple metrics',
      'Max User Weight': '350 lbs',
      'Dimensions': '86" x 22" x 46"',
    },
  },
  {
    id: '21',
    name: 'Cable Machine Station',
    description: 'Versatile cable machine for countless exercises. Dual weight stacks for independent or combined workouts.',
    price: 1799.99,
    image: '/products/selection-700-1.jpg',
    images: [
      '/products/selection-700-1.jpg',
      '/products/selection-700-2.jpg',
      '/products/selection-700-3.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      'Dual 150 lb weight stacks',
      'Multiple attachment points',
      'Smooth cable system',
      'Various handle attachments included',
      'Stable base',
    ],
    specifications: {
      'Weight Stacks': '2 x 150 lbs',
      'Height': '85 inches',
      'Frame': 'Heavy-duty steel',
      'Warranty': '5 years frame',
    },
  },
  {
    id: '22',
    name: 'Leg Press Machine',
    description: 'Heavy-duty leg press for building lower body strength. Smooth linear bearing system.',
    price: 1699.99,
    image: '/products/pure-strength-leg-press-1.jpg',
    images: [
      '/products/pure-strength-leg-press-1.jpg',
      '/products/pure-strength-leg-press-2.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      '45-degree angle',
      'Linear bearing system',
      'Adjustable back pad',
      'Weight plate storage',
      'Non-slip footplate',
    ],
    specifications: {
      'Max Weight Capacity': '1000 lbs',
      'Footplate': '18" x 18"',
      'Frame': 'Commercial steel',
      'Dimensions': '72" x 48" x 60"',
    },
  },
  {
    id: '23',
    name: 'Chest Press Machine',
    description: 'Iso-lateral chest press for balanced muscle development. Convergent motion path.',
    price: 1499.99,
    image: '/products/pure-strength-chest-press-1.jpg',
    images: [
      '/products/pure-strength-chest-press-1.jpg',
      '/products/pure-strength-chest-press-2.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      'Iso-lateral movement',
      'Convergent motion path',
      'Adjustable seat',
      'Multiple grip positions',
      'Weight plate holders',
    ],
    specifications: {
      'Max Weight': '400 lbs per side',
      'Seat Adjustment': '10 positions',
      'Frame': 'Heavy-duty steel',
      'Dimensions': '68" x 52" x 48"',
    },
  },
  {
    id: '24',
    name: 'Olympic Barbell Set',
    description: 'Professional Olympic barbell with weight plates. Perfect for powerlifting and Olympic lifting.',
    price: 599.99,
    image: '/products/olympic-barbell-set.jpg',
    images: [
      '/products/olympic-barbell-set.jpg',
    ],
    category: 'Equipment',
    rating: 5,
    inStock: true,
    features: [
      '7-foot Olympic barbell (45 lbs)',
      '300 lbs of bumper plates',
      'Rotating sleeves',
      'Knurled grip',
      'Includes collars',
    ],
    specifications: {
      'Barbell Length': '7 feet',
      'Barbell Weight': '45 lbs',
      'Total Weight': '345 lbs',
      'Plate Sizes': '45, 35, 25, 10 lbs',
    },
  },

  // ============ MORE CLOTHES (Products 25-27) ============
  {
    id: '25',
    name: 'Men\'s Navy Performance Tee',
    description: 'Classic navy training tee with moisture-wicking technology. Perfect for all types of workouts.',
    price: 42.99,
    image: '/products/L-Model-Power-Oversized-Tee-Navy-1.webp',
    images: [
      '/products/L-Model-Power-Oversized-Tee-Navy-1.webp',
      '/products/L-Model-Power-Oversized-Tee-Navy-2.webp',
      '/products/L-Model-Power-Oversized-Tee-Navy-3.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Navy blue colorway',
      'Moisture-wicking fabric',
      'Athletic fit',
      'Quick-dry technology',
      'Breathable material',
    ],
    specifications: {
      'Material': '88% Polyester, 12% Spandex',
      'Sizes': 'S, M, L, XL, XXL',
      'Care': 'Machine washable',
      'Fit': 'Athletic',
    },
  },
  {
    id: '26',
    name: 'Men\'s Pirate Black Training Tee',
    description: 'Sleek black performance tee. Premium fabric with excellent stretch and recovery.',
    price: 44.99,
    image: '/products/L-Model-Power-Oversized-Tee-Pirate-Black-1.webp',
    images: [
      '/products/L-Model-Power-Oversized-Tee-Pirate-Black-1.webp',
      '/products/L-Model-Power-Oversized-Tee-Pirate-Black-2.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Pirate black color',
      'Premium stretch fabric',
      'Anti-odor treatment',
      'Flatlock seams',
      'Athletic cut',
    ],
    specifications: {
      'Material': '90% Polyester, 10% Elastane',
      'Sizes': 'S, M, L, XL',
      'Care': 'Machine wash cold',
      'Fit': 'Athletic',
    },
  },
  {
    id: '27',
    name: 'Men\'s Glacial Blue Training Tee',
    description: 'Fresh glacial blue training shirt. Lightweight and breathable for intense workouts.',
    price: 43.99,
    image: '/products/L-Model-Power-Oversized-Tee-Glacial-Blue-1.webp',
    images: [
      '/products/L-Model-Power-Oversized-Tee-Glacial-Blue-1.webp',
      '/products/L-Model-Power-Oversized-Tee-Glacial-Blue-2.webp',
      '/products/L-Model-Power-Oversized-Tee-Glacial-Blue-3.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Glacial blue colorway',
      'Lightweight construction',
      'Breathable mesh panels',
      'Quick-dry fabric',
      'Comfortable fit',
    ],
    specifications: {
      'Material': '85% Polyester, 15% Spandex',
      'Sizes': 'S, M, L, XL, XXL',
      'Care': 'Machine washable',
      'Fit': 'Regular',
    },
  },

  // ============ SPORTS BRAS (Products 28-31) ============
  {
    id: '28',
    name: 'Women\'s Galvanise Sports Bra - Black',
    description: 'High-support sports bra with removable pads. Perfect for high-intensity workouts and training.',
    price: 39.99,
    image: '/products/S-Model-Galvanise-Sports-Bra-2.0-Black-1.webp',
    images: [
      '/products/S-Model-Galvanise-Sports-Bra-2.0-Black-1.webp',
      '/products/S-Model-Galvanise-Sports-Bra-2.0-Black-2.webp',
      '/products/S-Model-Galvanise-Sports-Bra-2.0-Black-3.webp',
      '/products/S-Model-Galvanise-Sports-Bra-2.0-Black-4.webp',
      '/products/S-Model-Galvanise-Sports-Bra-2.0-Black-5.webp',
      '/products/Features-Galvanise-Sports-Bra-2.0-Black.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'High support level',
      'Removable padding',
      'Moisture-wicking fabric',
      'Adjustable straps',
      'Breathable design',
    ],
    specifications: {
      'Material': '77% Nylon, 23% Elastane',
      'Sizes': 'XS, S, M, L, XL',
      'Support': 'High',
      'Care': 'Hand wash recommended',
    },
  },
  {
    id: '29',
    name: 'Women\'s Accelerate Sports Bra - Black',
    description: 'Seamless sports bra with medium support. Ideal for running, cycling, and gym workouts.',
    price: 34.99,
    image: '/products/S-Model-Accelerate-Sports-Bra-Black-6.webp',
    images: [
      '/products/S-Model-Accelerate-Sports-Bra-Black-6.webp',
      '/products/S-Model-Accelerate-Sports-Bra-Black-10.webp',
      '/products/Features-Accelerate-Sports-Bra-Black.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Seamless construction',
      'Medium support',
      'Quick-dry fabric',
      'No-dig straps',
      'Comfortable fit',
    ],
    specifications: {
      'Material': '92% Nylon, 8% Elastane',
      'Sizes': 'XS, S, M, L',
      'Support': 'Medium',
      'Care': 'Machine washable',
    },
  },
  {
    id: '30',
    name: 'Women\'s Stamina Sports Bra - Candy Pink',
    description: 'Vibrant pink sports bra with supportive design. Features moisture-wicking technology.',
    price: 36.99,
    image: '/products/S-Campaign-Stamina-Sports-Bra-Candy-Pink-5.webp',
    images: [
      '/products/S-Campaign-Stamina-Sports-Bra-Candy-Pink-5.webp',
      '/products/S-Campaign-Stamina-Sports-Bra-Candy-Pink-7.webp',
      '/products/S-Campaign-Stamina-Sports-Bra-Candy-Pink-8.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Vibrant candy pink color',
      'Medium-high support',
      'Moisture-wicking',
      'Comfortable straps',
      'Flexible fit',
    ],
    specifications: {
      'Material': '80% Nylon, 20% Elastane',
      'Sizes': 'XS, S, M, L, XL',
      'Support': 'Medium-High',
      'Care': 'Machine wash cold',
    },
  },
  {
    id: '31',
    name: 'Women\'s Velocity Sports Bra - Dark Moss',
    description: 'Premium sports bra in dark moss color. High-support design for intense training sessions.',
    price: 41.99,
    image: '/products/S-Campaign-Velocity-Sports-Bra-Dark-Moss-2.webp',
    images: [
      '/products/S-Campaign-Velocity-Sports-Bra-Dark-Moss-2.webp',
      '/products/S-Model-Velocity-Sports-Bra-Dark-Moss-1.webp',
      '/products/S-Model-Velocity-Sports-Bra-Dark-Moss-2.webp',
      '/products/S-Model-Velocity-Sports-Bra-Dark-Moss-3.webp',
      '/products/S-Model-Velocity-Sports-Bra-Dark-Moss-4.webp',
      '/products/S-Model-Velocity-Sports-Bra-Dark-Moss-5.webp',
    ],
    category: 'Clothing',
    rating: 5,
    inStock: true,
    features: [
      'Dark moss colorway',
      'High support level',
      'Moisture-wicking fabric',
      'Breathable mesh panels',
      'Adjustable fit',
    ],
    specifications: {
      'Material': '75% Nylon, 25% Elastane',
      'Sizes': 'XS, S, M, L, XL',
      'Support': 'High',
      'Care': 'Machine wash cold',
    },
  },
];

export default sportsProducts;
